### ISSUE TITLE
os.getlogin() - OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bcoles** [initstring/uptux#1]
```
[*] Starting module at 2019-02-13-17.09.09


Host: linux-mint-19-2
OS: Linux, #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018
Kernel: 4.15.0-20-generic
Traceback (most recent call last):
  File "./uptux.py", line 748, in <module>
    main()
  File "./uptux.py", line 741, in main
    check_handler(check, check_name, check_desc)
  File "./uptux.py", line 114, in check_handler
    check()
  File "./uptux.py", line 406, in uptux_check_sysinfo
    tee("Current user: {} (UID {} GID {})".format(os.getlogin(),
OSError: [Errno 2] No such file or directory

```

See: https://bugs.python.org/issue584566

Fix:

```diff
diff --git a/uptux.py b/uptux.py
index 70e39c4..41efa8d 100755
--- a/uptux.py
+++ b/uptux.py
@@ -12,6 +12,7 @@ in restricted shells is a pain.
 
 
 import os
+import pwd
 import sys
 import argparse
 import datetime
@@ -403,7 +404,7 @@ def uptux_check_sysinfo():
     tee("Host: {}".format(uname[1]))
     tee("OS: {}, {}".format(uname[0], uname[3]))
     tee("Kernel: {}".format(uname[2]))
-    tee("Current user: {} (UID {} GID {})".format(os.getlogin(),
+    tee("Current user: {} (UID {} GID {})".format(pwd.getpwuid(os.geteuid())[0],
                                                   os.getuid(),
                                                   os.getgid()))
     tee("Member of following groups:\n  {}".format(shell_exec('groups')))
```

**Comment by initstring** [comment]
Thank you very much for taking the time to submit this!

I will have a bit of time to review later this week. Apologies for the delay, just in the middle of some projects.

Thanks again for your help and patience!

**Comment by initstring** [comment]
Thanks again for pointing this out.

I see in the python3 docs [here](https://docs.python.org/3/library/os.html) that they recommend using getpass.getlogin(), which first checks environment variables and then falls back to your recommended getpwuid:

getlogin()
Return the name of the user logged in on the controlling terminal of the process. For most purposes, it is more useful to use getpass.getuser() since the latter checks the environment variables LOGNAME or USERNAME to find out who the user is, and falls back to pwd.getpwuid(os.getuid())[0] to get the login name of the current real user id.

I just installed Mint 17 in a VM and tested, and this seems to work.

I think I am going to go with that method. Thanks again for bringing attention to this!

**Comment by initstring** [comment]
(edit to correct my goof up)

I believe this should now work for you. Let me know if this is not the case.

**Comment by bcoles** [comment]
Yes, `getpass.getuser()` works.
